const POPULATION_UPDATED = 'POPULATION_CREATED'
const EMISSION_UPDATED = 'EMISSION_UPDATED'
const COUNTRYSTATS_UPDATED = 'COUNTRYSTATS_UPDATED'
const TOP_EMISSIONS_UPDATED = 'TOP_EMISSIONS_UPDATED'
const TOP_PER_CAPITA_UPDATED = 'TOP_PER_CAPITA_UPDATED'

module.exports = {
  POPULATION_UPDATED,
  EMISSION_UPDATED,
  COUNTRYSTATS_UPDATED,
  TOP_EMISSIONS_UPDATED,
  TOP_PER_CAPITA_UPDATED
}
