const POPULATION_UPDATED = 'POPULATION_CREATED'
const EMISSION_UPDATED = 'EMISSION_UPDATED'
const COUNTRYSTATS_UPDATED = 'COUNTRYSTATS_UPDATED'

module.exports = { POPULATION_UPDATED, EMISSION_UPDATED, COUNTRYSTATS_UPDATED }